version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: taskmanager
      POSTGRES_PASSWORD: taskmanager
      POSTGRES_DB: taskmanager
    ports:
      - "7400:7400"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql 
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      FLASK_ENV: production
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - .:/app  

networks:
  app-network:

volumes:
  postgres_data:
